### ISSUE TITLE
Privacy info

### ISSUE THREAD

**Issue by rackker** [shotaokb/MouseOverTooltip#13]
Do you collect and store any data collected by the tooltip or associated with the data sources on the GDS dashboard?

**Comment by shotaokb** [comment]
No. Tooltips only display the items set in the Style property, they do not collect any data, including on the GDS dashboard.
Please also refer to the Privacy Policy in the official documentation.
https://datastudio.google.com/reporting/b9596a2a-d10a-4916-a79b-c8ccb03c9138/page/KKHTB
