### ISSUE TITLE
Icon disappeared

### ISSUE THREAD

**Issue by jgnunes** [shotaokb/MouseOverTooltip#21]
Hi, 

I have been successfully using the tool until today, when the icons disappeared from all my datastudio pages. 

Here is one example: 
![image](https://user-images.githubusercontent.com/22843614/129234161-39db3180-cc18-40a7-a02c-23d59e750484.png)

The box is there, but it is invisible. I tried to change the default options, but with no success.

**Comment by shotaokb** [comment]
@jgnunes 
I was able to reproduce the same problem as yours in my environment.
I will check here and fix it.

**Comment by shotaokb** [comment]
Progress report
When displaying the Tooltip, I got an error like the one in the log below.
[datastudio.google.com-1628858191528.log](https://github.com/shotaokb/MouseOverTooltip/files/6982441/datastudio.google.com-1628858191528.log)
I have not made any recent changes to the source code.
I will continue to try to solve the problem.

**Comment by jgnunes** [comment]
Thanks for the updates, @shotaokb. Looking forward to hearing back from you, and congratulations for the tool, it has been really useful to me!

**Comment by Joe-In-Ohio** [comment]
Same issue occurred for me to. This is a great tool @shotaokb and hope you are able to fix the issue quickly.

Keep up the great work!

**Comment by shotaokb** [comment]
Progress report
Due to recent changes to Data Studio, visualizations with no data elements are no longer supported.
This seems to be the cause of the problem and we will fix it.

**Comment by shotaokb** [comment]
A fix for this issue has been completed.
Due to the specifications of Google Data Studio, it will take around 12 hours for the change to be applied.

Also, the Data Dimension setting is now required to use the MouseOver Tooltip.
You will need to set up dummy data.
Please be assured that this visualisation continues to take no data from the user.

**Comment by jgnunes** [comment]
Thanks, @shotaokb. That solved the issue from my side. It's working perfectly.
