### ISSUE TITLE
New Change to Looker Studio requires Metric field

### ISSUE THREAD

**Issue by KonstantinDamn** [shotaokb/MouseOverTooltip#23]
Hello,

a new change to Looker Studio now requires any visualisation to have a metric in addition to a dimension. Therefore, MouseOver Tooltip does no longer work. This could easily be resolved by adding a dummy metric.

Thank you and best regards,
Konstantin

**Comment by shotaokb** [comment]
@KonstantinDamn 
Thanks for passing on the information.
We will be responding to this in the near future.
If you know, could you please provide the URL of the web page announcing the change?

**Comment by KonstantinDamn** [comment]
I seem to have been mistaken, the error was due to a change of a datasource rather than a general one.
